package hrmsystem;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 *@author Kenneth-29
 */
public class UserInterface extends javax.swing.JFrame {
    
    /**
     * Object Instantiation:
     */
    private InputOutput io;  
    private Search search;
    private Search search2;
    //list of all records:
    private ArrayList<Employee> records = new ArrayList<>();
    //Management department list
    private ArrayList<Employee> resultsManagement;
    //Marketing department list
    private ArrayList<Employee> resultsMarketing;
    //HR department list
    private ArrayList<Employee> resultsHumanResource;    
    //Accounts department list
    private ArrayList<Employee> resultsAccounts;  
    //Support department list
    private ArrayList<Employee> resultsSupport;
    //Temporary department list
    private ArrayList<Employee> resultsTemp;
    
    private ArrayList<Employee> resultsGender;
    private ArrayList<Employee> resultsCity;
   
    
    /**
     * Creates new form UserInterface
     */
    public UserInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        summaryArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        managementField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        marketingField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        hrField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        accField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        supportField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        totalField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tempField = new javax.swing.JTextField();
        sumBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        salaryArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        allSalariesArea = new javax.swing.JTextArea();
        displayGrossBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        searchArea = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        genderCount = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        searchArea2 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        cityCount = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        summaryArea.setColumns(20);
        summaryArea.setRows(5);
        jScrollPane1.setViewportView(summaryArea);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel1.setText("Company Name:");

        managementField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managementFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel3.setText("Employee Breakdown (Numbers):");

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setText("Management:");

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel5.setText("Envies DeTour Pty Ltd");

        jLabel7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel7.setText("Marketing:");

        jLabel8.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel8.setText("Human Resource:");

        jLabel9.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel9.setText("Accounts:");

        jLabel10.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel10.setText("Support Staff:");

        jLabel11.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel11.setText("Total:");

        jLabel21.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel21.setText("Temp Staff:");

        sumBtn.setText("Show Summary");
        sumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(managementField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(marketingField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                                        .addComponent(hrField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(accField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(supportField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tempField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel3)))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sumBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(managementField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(marketingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(hrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(accField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(supportField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(tempField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sumBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Employee Summary", jPanel1);

        jLabel12.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel12.setText("Employee ID:");

        jLabel15.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel15.setText("Enter Employee ID (integer) to Calculate Salary:");

        salaryArea.setColumns(20);
        salaryArea.setRows(5);
        jScrollPane2.setViewportView(salaryArea);

        jButton1.setText("Calculate Salary");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(209, 209, 209))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(93, 93, 93)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Salary Calculation", jPanel2);

        allSalariesArea.setColumns(20);
        allSalariesArea.setRows(5);
        jScrollPane3.setViewportView(allSalariesArea);

        displayGrossBtn.setText("Display Gross Salaries");
        displayGrossBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayGrossBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayGrossBtn)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayGrossBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Gross Salaries", jPanel3);

        searchArea.setColumns(20);
        searchArea.setRows(5);
        jScrollPane4.setViewportView(searchArea);

        jLabel17.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel17.setText("Filter by Gender:");

        jLabel18.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel18.setText("Filter by City:");

        buttonGroup1.add(male);
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        buttonGroup1.add(female);
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel19.setText("Results Returned:");

        genderCount.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        genderCount.setText("0");

        cityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityFieldActionPerformed(evt);
            }
        });

        searchArea2.setColumns(20);
        searchArea2.setRows(5);
        jScrollPane5.setViewportView(searchArea2);

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cityCount.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        cityCount.setText("0");

        jLabel23.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel23.setText("Results Returned:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(male)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(41, 41, 41)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(genderCount, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(female)
                                .addGap(313, 313, 313)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cityCount, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(genderCount)
                    .addComponent(jLabel23)
                    .addComponent(cityCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(male)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(female))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );

        jTabbedPane1.addTab("Search", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void managementFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managementFieldActionPerformed
        
    }//GEN-LAST:event_managementFieldActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        
        searchArea.setEditable(false);
        
        try {
        //Open File and read records into list
        io = new InputOutput();
        io.openFile();
        records = io.readIntoArray();
        io.closeFile();
            
        search = new Search();
        
        resultsGender = new ArrayList<>();
        resultsGender = search.searchByGender('M', records, resultsGender);    
         
        searchArea.setText("ID\tName\tSurname");
        searchArea.setText(searchArea.getText()+"\n====================================\n");
        //Output Search result:
        for(Employee emp:resultsGender)
        {
            searchArea.setText(searchArea.getText()+emp.getEmployeeId()+"\t"+emp.getFirstName()+"\t"+emp.getLastName()+"\n");
        }
        
        genderCount.setText(""+resultsGender.size());
                        
        } 
        catch (IOException ex) 
        
        {
            Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        searchArea.setEditable(false);
        
        try {
        //Open File and read records into list
        io = new InputOutput();
        io.openFile();
        records = io.readIntoArray();
        io.closeFile();
            
        search = new Search();
        
        resultsGender = new ArrayList<>();
        resultsGender = search.searchByGender('F', records, resultsGender);    
         
        searchArea.setText("ID\tName\tSurname");
        searchArea.setText(searchArea.getText()+"\n====================================\n");
        //Output Search result:
        for(Employee emp:resultsGender)
        {
            searchArea.setText(searchArea.getText()+emp.getEmployeeId()+"\t"+emp.getFirstName()+"\t"+emp.getLastName()+"\n");
        }
        
        genderCount.setText(""+resultsGender.size());
                        
        } 
        catch (IOException ex) 
        
        {
            Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_femaleActionPerformed

    private void cityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityFieldActionPerformed

    private void sumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumBtnActionPerformed
        
        summaryArea.setEditable(false);
        managementField.setEditable(false);
        marketingField.setEditable(false);
        hrField.setEditable(false);
        accField.setEditable(false);
        supportField.setEditable(false);
        tempField.setEditable(false);
        totalField.setEditable(false);
        
        try 
        {
            //Open File and read records into list
            io = new InputOutput();
            io.openFile();
            records = io.readIntoArray();
            io.closeFile();
            
            //Output Rsults to screen:
            search = new Search();
            summaryArea.setText("Management:");
            summaryArea.setText(summaryArea.getText()+"\n===========\n");
            
            resultsManagement = new ArrayList<>();          
            resultsManagement = search.searchEmloyeeType("Management", records, resultsManagement);
            for(Employee emp: resultsManagement)
            {
                summaryArea.setText(summaryArea.getText()+"id: "+emp.getEmployeeId()+" | "+emp.getLastName()+", "+emp.getFirstName()+" ("+emp.getTitleOfEmployment()+")"+"\n");
            }
            /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
            summaryArea.setText(summaryArea.getText()+"\nMarketing");
            summaryArea.setText(summaryArea.getText()+"\n=========\n");
            
            resultsMarketing = new ArrayList<>();          
            resultsMarketing = search.searchEmloyeeType("Marketing", records, resultsMarketing);
            for(Employee emp: resultsMarketing)
            {
                summaryArea.setText(summaryArea.getText()+"id: "+emp.getEmployeeId()+" | "+emp.getLastName()+", "+emp.getFirstName()+" ("+emp.getTitleOfEmployment()+")"+"\n");
            }
            /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
            summaryArea.setText(summaryArea.getText()+"\nHuman Resource");
            summaryArea.setText(summaryArea.getText()+"\n==============\n");
            
            resultsHumanResource = new ArrayList<>();          
            resultsHumanResource = search.searchEmloyeeType("Human Resource", records, resultsHumanResource);
            for(Employee emp: resultsHumanResource)
            {
                summaryArea.setText(summaryArea.getText()+"id: "+emp.getEmployeeId()+" | "+emp.getLastName()+", "+emp.getFirstName()+" ("+emp.getTitleOfEmployment()+")"+"\n");
            }
            ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
            summaryArea.setText(summaryArea.getText()+"\nAccounts");
            summaryArea.setText(summaryArea.getText()+"\n========\n");
            
            resultsAccounts = new ArrayList<>();          
            resultsAccounts = search.searchEmloyeeType("Accounts", records, resultsAccounts);
            for(Employee emp: resultsAccounts)
            {
                summaryArea.setText(summaryArea.getText()+"id: "+emp.getEmployeeId()+" | "+emp.getLastName()+", "+emp.getFirstName()+" ("+emp.getTitleOfEmployment()+")"+"\n");
            }
            ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
            summaryArea.setText(summaryArea.getText()+"\nSupport Staff");
            summaryArea.setText(summaryArea.getText()+"\n============\n");
            
            resultsSupport = new ArrayList<>();          
            resultsSupport = search.searchEmloyeeType("Support Staff", records, resultsSupport);
            for(Employee emp: resultsSupport)
            {
                summaryArea.setText(summaryArea.getText()+"id: "+emp.getEmployeeId()+" | "+emp.getLastName()+", "+emp.getFirstName()+" ("+emp.getTitleOfEmployment()+")"+"\n");
            }
            ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
            summaryArea.setText(summaryArea.getText()+"\nTemporary Staff");
            summaryArea.setText(summaryArea.getText()+"\n=============\n");
            
            resultsTemp = new ArrayList<>();          
            resultsTemp = search.searchEmloyeeType("Temporary Staff", records, resultsTemp);
            for(Employee emp: resultsTemp)
            {
                summaryArea.setText(summaryArea.getText()+"id: "+emp.getEmployeeId()+" | "+emp.getLastName()+", "+emp.getFirstName()+" ("+emp.getTitleOfEmployment()+")"+"\n");
            }
            ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
            
            /**
             * Count and display the number of each Employee Type:
             */
            managementField.setText(""+resultsManagement.size());
            marketingField.setText(""+resultsMarketing.size());
            hrField.setText(""+resultsHumanResource.size());
            accField.setText(""+resultsAccounts.size());
            supportField.setText(""+resultsSupport.size());
            tempField.setText(""+resultsTemp.size());
            
            int total = resultsManagement.size()+resultsMarketing.size()+resultsHumanResource.size()+resultsAccounts.size()+resultsSupport.size()+resultsTemp.size();
            totalField.setText(""+total);
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_sumBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        salaryArea.setEditable(false);
        
        try {
            //Open File and read records into list
            io = new InputOutput();
            io.openFile();
            records = io.readIntoArray();
            io.closeFile();
            
            if(idField.getText().equals(""))
            {
                salaryArea.setText("<<Please enter a valid id of type int to search for an employee.");   
            }else
            {
                int id = Integer.parseInt(idField.getText());
            
            search = new Search();
            
            int index = search.searchEmployeeById(id, records);
            
            if(index == -1)
            {
                salaryArea.setText("<<No result found for ID "+id+".");   
            }else
            {
                Employee emp = records.get(index);
                
                salaryArea.setText("Employee ID: "+id); 
                salaryArea.setText(salaryArea.getText()+"\n=============\n"); 
                
                salaryArea.setText(salaryArea.getText()+"Name: "+emp.getFirstName());
                salaryArea.setText(salaryArea.getText()+"\nSurname: "+emp.getLastName());
                salaryArea.setText(salaryArea.getText()+"\nDepartment: "+emp.getDEPARTMENT());
                salaryArea.setText(salaryArea.getText()+"\nPosition: "+emp.getTitleOfEmployment()+"\n");
                
                salaryArea.setText(salaryArea.getText()+"\nBase");
                salaryArea.setText(salaryArea.getText()+"\n-------");
                salaryArea.setText(salaryArea.getText()+"\nHours Worked:\t\t"+emp.getHoursWorked()+" hrs");
                salaryArea.setText(salaryArea.getText()+"\nPay Rate:\t\t"+String.format("%.2f",emp.getRateOfPay())+"( per hour)");
                salaryArea.setText(salaryArea.getText()+"\nBase Salary:\t\t"+"P"+String.format("%.2f",emp.getSalary()));
                
                salaryArea.setText(salaryArea.getText()+"\n\nIncentives");
                salaryArea.setText(salaryArea.getText()+"\n-------------");
                salaryArea.setText(salaryArea.getText()+"\nCar Allowance:\t\t"+"P"+String.format("%.2f",emp.getCarAllowance())+" ("+emp.getCarAllowanceRate()+"%)");
                salaryArea.setText(salaryArea.getText()+"\nGratuity:\t\t"+"P"+String.format("%.2f",emp.getMonthlyGratuity()));
                
                salaryArea.setText(salaryArea.getText()+"\n\nTotal:\t\t"+"P"+String.format("%.2f",emp.calculateGrossSalary()));
            
            }
   
            }
            
        } catch (IOException ex) {
            Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void displayGrossBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayGrossBtnActionPerformed
        
        try {
            //Open File and read records into list
            io = new InputOutput();
            io.openFile();
            records = io.readIntoArray();
            io.closeFile();
            
            allSalariesArea.setText("ID\t\tName\t\tSurname\t\tGross Salary");
            allSalariesArea.setText(allSalariesArea.getText()+"\n======================================================================================\n");
            //Loop through records to show gross salaries:
            for(Employee emp: records)
            {
                allSalariesArea.setText(allSalariesArea.getText()+emp.getEmployeeId()+"\t\t"+emp.getFirstName()+"\t\t"+emp.getLastName()+"\t\t"+"P"+String.format("%.2f",emp.calculateGrossSalary())+"\n");
            }
            
                        
        } catch (IOException ex) {
            Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_displayGrossBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        searchArea2.setEditable(false);
        
        try {
        //Open File and read records into list
        io = new InputOutput();
        io.openFile();
        records = io.readIntoArray();
        io.closeFile();
            
        search2 = new Search();
        
        resultsCity = new ArrayList<>();

        if(cityField.getText().equals(""))
        {
            searchArea2.setText("<<Enter a valid City name to search.");
        }else
        {
            String city = cityField.getText();
            
            resultsCity = search2.searchByCity(city, records, resultsCity);
            
            if(resultsCity.isEmpty())
            {
                searchArea2.setText("<<No results found for entered city.");
            }
            
            searchArea2.setText("ID\tName\tSurname");
            searchArea2.setText(searchArea2.getText()+"\n====================================\n");
            //Output Search result:
            for(Employee emp:resultsCity)
            {
                searchArea2.setText(searchArea2.getText()+emp.getEmployeeId()+"\t"+emp.getFirstName()+"\t"+emp.getLastName()+"\n");
            }
        
            cityCount.setText(""+resultsCity.size());
        }
          
        } 
        catch (IOException ex) 
        
        {
            Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accField;
    private javax.swing.JTextArea allSalariesArea;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cityCount;
    private javax.swing.JTextField cityField;
    private javax.swing.JButton displayGrossBtn;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel genderCount;
    private javax.swing.JTextField hrField;
    private javax.swing.JTextField idField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField managementField;
    private javax.swing.JTextField marketingField;
    private javax.swing.JTextArea salaryArea;
    private javax.swing.JTextArea searchArea;
    private javax.swing.JTextArea searchArea2;
    private javax.swing.JButton sumBtn;
    private javax.swing.JTextArea summaryArea;
    private javax.swing.JTextField supportField;
    private javax.swing.JTextField tempField;
    private javax.swing.JTextField totalField;
    // End of variables declaration//GEN-END:variables
}
